### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by Egida** [DrankRock/ProxyScrape-And-Check#1]
Hi, how to use?
```
root@localhost:~/ProxyScrape-And-Check# python3 ProxyScrape.py
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
root@localhost:~/ProxyScrape-And-Check# 
```

**Comment by DrankRock** [comment]
Hello, I have never seen this issue, did you install the packages using `python3 -m pip install -r requirements.txt` ?

Edit : By the way, what version of python are you using? I had issues using a similar project with Python 3.9 and 3.10

**Comment by Egida** [comment]
> Hello, I have never seen this issue, did you install the packages using `python3 -m pip install -r requirements.txt` ?
> 
> Edit : By the way, what version of python are you using? I had issues using a similar project with Python 3.9 and 3.10

of course
Python 3.9.5

**Comment by Egida** [comment]
> Hello, I have never seen this issue, did you install the packages using `python3 -m pip install -r requirements.txt` ?
> 
> Edit : By the way, what version of python are you using? I had issues using a similar project with Python 3.9 and 3.10

I tried it on a linux graphical environment - it works, but how to run it on the cli version?

**Comment by DrankRock** [comment]
By "cli version" do you mean a version without the GUI ? I have not made one, I will add one in the next few days.
My apologies, I did not think it would be necessary

**Comment by DrankRock** [comment]
@Egida I updated ProxyScrape, there is now a terminal version. You can simply run it by using `python ProxyScrape.py -te` and it will launch it with the regular parameters (Timeout = 10, scraping = True, checking = True, website = "https://www.google.com", threads = 50)
You can see all arguments with `python ProxyScape.py -h`

I have not yet made the possibility to insert proxies with input file, to output details to a logfile or to output the working proxies to an output file. I will do it in the next few days.

**Comment by Egida** [comment]
> @Egida I updated ProxyScrape, there is now a terminal version. You can simply run it by using `python ProxyScrape.py -te` and it will launch it with the regular parameters (Timeout = 10, scraping = True, checking = True, website = "https://www.google.com", threads = 50) You can see all arguments with `python ProxyScape.py -h`
> 
> I have not yet made the possibility to insert proxies with input file, to output details to a logfile or to output the working proxies to an output file. I will do it in the next few days.

root@localhost:~/ProxyScrape-And-Check# python ProxyScrape.py -te -ti 10 -th 50
[Mon May  9 17:13:30 2022] - Starting terminal version of ProxyScrape..
Traceback (most recent call last):
  File "/root/ProxyScrape-And-Check/ProxyScrape.py", line 273, in <module>
    terminal(args)
  File "/root/ProxyScrape-And-Check/ProxyScrape.py", line 236, in terminal
    for files in args.input :
TypeError: 'NoneType' object is not iterable
